"""
core/scene_builder.py — VisionAssist Scene Builder Layer (v2 — Canonical JSON)
================================================================================

PURPOSE
-------
Transforms raw, noisy per-frame YOLO+OCR detections into a stable, canonical
JSON scene object that is the single source of truth for all downstream systems:
Alerts, Memory, Voice Commands, NanoClaw, OpenClaw, Navigation.

ARCHITECTURE
------------
YOLO Detection
  ↓
SceneBuilder.process_frame()   ← YOU ARE HERE
  ↓
Canonical Scene JSON
  ↓  ↓  ↓  ↓
Alerts / Memory / Speech / Future Modules

CANONICAL SCENE SCHEMA
----------------------
{
  "timestamp":  1715000000.0,
  "objects": [
    {"label": "person",  "position": "center", "confidence": 0.94, "priority": "high"},
    {"label": "bottle",  "position": "left",   "confidence": 0.81, "priority": "normal"}
  ],
  "text": [
    {"content": "EXIT", "position": "right", "confidence": 0.88, "source_object": "sign"}
  ],
  "alerts":     [],
  "navigation": {},
  "metadata":   {"frame_index": 410}
}

DESIGN PRINCIPLES
-----------------
- SceneBuilder is a NORMALIZER, not a reasoner.
- Speech is a PRESENTATION LAYER — generated by summarize_scene(), not here.
- Real-time safe: all ops are O(n), no I/O, no threads.
- Forward-compatible: schema fields are stable for NanoClaw/OpenClaw integration.
"""

import time
from collections import defaultdict


# ---------------------------------------------------------------------------
# Priority tables
# ---------------------------------------------------------------------------

# Numeric priority (lower = higher priority) — used for sorting
_PRIORITY_RANK: dict[str, int] = {
    "person":   1,
    "car":      2, "bus":    2, "truck":   2,
    "bicycle":  3, "motorcycle": 3,
    "chair":    4, "couch":  4, "bed":     4, "table":   4,
    "dog":      5, "cat":    5,
    "bottle":   6, "cup":    6, "bowl":    6,
    "laptop":   7, "cell phone": 7, "remote": 7,
    "book":     8, "clock":  8,
}

# Human-readable priority tier (for the JSON schema)
def _priority_tier(label: str) -> str:
    rank = _PRIORITY_RANK.get(label, 99)
    if rank <= 2:
        return "critical"
    if rank <= 3:
        return "high"
    return "normal"

# Direction → human-readable phrase (for summarize_scene)
_DIRECTION_PHRASES: dict[str, str] = {
    "left":   "on the left",
    "center": "ahead",
    "right":  "on the right",
}

# Persistence: frames an object may be absent before being dropped from scene
_DEFAULT_PERSISTENCE_FRAMES: int = 8

# Max objects in a single spoken sentence
_MAX_OBJECTS_IN_SENTENCE: int = 3


# ---------------------------------------------------------------------------
# Internal tracking record
# ---------------------------------------------------------------------------

class _TrackedObject:
    """
    Tracks one (label, direction) pair across frames.
    Separate tracking per direction so "bottle left" and "bottle right"
    are independent facts.
    """
    __slots__ = ("label", "direction", "confidence", "last_seen_frame")

    def __init__(self, label: str, direction: str, confidence: float, frame: int):
        self.label = label
        self.direction = direction
        self.confidence = confidence
        self.last_seen_frame = frame


# ---------------------------------------------------------------------------
# SceneBuilder
# ---------------------------------------------------------------------------

class SceneBuilder:
    """
    Converts raw per-frame YOLO detections into a canonical JSON scene.

    The returned scene dict is the single source of truth consumed by all
    downstream systems.  Speech is produced by the module-level
    ``summarize_scene(scene)`` function — SceneBuilder never generates text.

    Parameters
    ----------
    persistence_frames : int
        Frames an object may be missing from YOLO before expiry.
        At 10–15 FPS, 8 frames ≈ ~0.6 s of hysteresis.
    cooldown_seconds : float
        Unused by SceneBuilder itself — kept for API compatibility with
        the AlertSystem which owns the cooldown.
    """

    def __init__(
        self,
        persistence_frames: int = _DEFAULT_PERSISTENCE_FRAMES,
        cooldown_seconds: float = 0.0,    # kept for API compat
    ):
        self.persistence_frames = persistence_frames
        self.cooldown_seconds = cooldown_seconds   # unused here, kept for compat

        # Live tracking state: (label, direction) → _TrackedObject
        self._tracked: dict[tuple[str, str], _TrackedObject] = {}

        # Change-detection snapshots
        self._last_snap_objects: frozenset = frozenset()
        self._last_snap_texts: frozenset = frozenset()

        self._frame_index: int = 0
        self._current_scene: dict = {}
        self._active_ocr: list = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def process_frame(self, detections: list[dict], ocr_results: list = None) -> dict:
        """
        Ingest one frame's YOLO detections and return the canonical scene JSON.

        Parameters
        ----------
        detections : list[dict]
            Each dict needs at minimum: class_name, direction, confidence.
        ocr_results : list, optional
            OCRResult objects (with .text, .position, .confidence, .source_object).

        Returns
        -------
        dict — canonical scene snapshot (see module docstring for schema).
        """
        self._frame_index += 1

        # ── 1. Update tracking ────────────────────────────────────────────────
        for det in detections:
            label     = det.get("class_name") or det.get("label", "unknown")
            direction = det.get("direction") or det.get("position", "center")
            confidence = float(det.get("confidence", 1.0))
            key = (label, direction)

            if key in self._tracked:
                self._tracked[key].last_seen_frame = self._frame_index
                self._tracked[key].confidence = confidence
            else:
                self._tracked[key] = _TrackedObject(label, direction, confidence, self._frame_index)

        # ── 2. Expire stale objects ───────────────────────────────────────────
        expired = [
            k for k, obj in self._tracked.items()
            if (self._frame_index - obj.last_seen_frame) > self.persistence_frames
        ]
        for k in expired:
            del self._tracked[k]

        # ── 3. Build canonical objects list ───────────────────────────────────
        # Group by (label) so we can produce one entry per unique label+position
        # Each surviving tracked entry becomes one item in "objects".
        object_list: list[dict] = []
        seen_labels_dirs: set[tuple] = set()

        sorted_tracked = sorted(
            self._tracked.values(),
            key=lambda o: (_PRIORITY_RANK.get(o.label, 99), o.label, o.direction)
        )

        for obj in sorted_tracked:
            key = (obj.label, obj.direction)
            if key not in seen_labels_dirs:
                seen_labels_dirs.add(key)
                object_list.append({
                    "label":      obj.label,
                    "position":   obj.direction,
                    "confidence": round(obj.confidence, 2),
                    "priority":   _priority_tier(obj.label),
                })

        # ── 4. Build canonical text list ──────────────────────────────────────
        if ocr_results is not None:
            self._active_ocr = ocr_results

        text_list: list[dict] = []
        for r in self._active_ocr:
            if hasattr(r, "text"):
                text_list.append({
                    "content":       r.text,
                    "position":      getattr(r, "position", "center"),
                    "confidence":    round(getattr(r, "confidence", 1.0), 2),
                    "source_object": getattr(r, "source_object", "sign"),
                })
            elif isinstance(r, dict):
                text_list.append({
                    "content":       r.get("text", ""),
                    "position":      r.get("position", "center"),
                    "confidence":    round(r.get("confidence", 1.0), 2),
                    "source_object": r.get("source_object", "sign"),
                })

        # ── 5. Assemble canonical scene ───────────────────────────────────────
        self._current_scene = {
            "timestamp":  time.time(),
            "objects":    object_list,
            "text":       text_list,
            "alerts":     [],       # populated by AlertSystem downstream
            "navigation": {},       # reserved for future navigation module
            "metadata":   {"frame_index": self._frame_index},
        }

        return self._current_scene

    def get_current_scene(self) -> dict:
        """Return the latest canonical scene snapshot."""
        return self._current_scene

    # Legacy compat: AlertSystem and voice commands previously used
    # scene["objects"] as dict[label → list[directions]].
    # This helper converts the new list format back for any code that
    # hasn't been migrated yet.
    def get_objects_legacy(self) -> dict[str, list[str]]:
        """
        Returns objects in the old dict-of-lists format for backward compat.
        Prefer consuming scene["objects"] directly.
        """
        grouped: dict[str, list[str]] = defaultdict(list)
        for obj in self._current_scene.get("objects", []):
            grouped[obj["label"]].append(obj["position"])
        return dict(grouped)


# ---------------------------------------------------------------------------
# summarize_scene() — PRESENTATION LAYER
# ---------------------------------------------------------------------------

def summarize_scene(scene: dict, max_objects: int = _MAX_OBJECTS_IN_SENTENCE) -> str:
    """
    Convert a canonical scene JSON dict → a natural English sentence for TTS.

    This is the ONLY place text is generated from scene data.
    All other systems consume the JSON directly.

    Examples
    --------
    >>> summarize_scene({"objects": [{"label":"person","position":"center",...}], "text": []})
    'Person ahead'

    >>> summarize_scene({"objects": [...], "text": [{"content":"EXIT","position":"right",...}]})
    'Person ahead, EXIT sign on the right'
    """
    objects = scene.get("objects", [])
    texts   = scene.get("text", [])

    if not objects and not texts:
        return ""

    phrases: list[str] = []

    # ── Objects ──────────────────────────────────────────────────────────────
    # Group by label so "bottle left" + "bottle right" → "bottles on the left and right"
    label_to_positions: dict[str, list[str]] = defaultdict(list)
    for obj in objects[:max_objects * 2]:   # scan a little extra before capping
        label_to_positions[obj["label"]].append(obj["position"])

    # Sort by priority rank, cap at max_objects unique labels
    sorted_labels = sorted(
        label_to_positions.keys(),
        key=lambda lbl: _PRIORITY_RANK.get(lbl, 99)
    )[:max_objects]

    for label in sorted_labels:
        positions = sorted(set(label_to_positions[label]))
        if len(positions) == 1:
            dir_phrase = _DIRECTION_PHRASES.get(positions[0], f"on the {positions[0]}")
        else:
            human = [_DIRECTION_PHRASES.get(p, f"on the {p}") for p in positions]
            dir_phrase = ", ".join(human[:-1]) + " and " + human[-1]

        is_plural = len(positions) > 1
        noun = _pluralize(label) if is_plural else label
        phrases.append(f"{noun} {dir_phrase}")

    # ── OCR text ─────────────────────────────────────────────────────────────
    for t in texts:
        content  = t.get("content", "").strip()
        position = t.get("position", "center")
        src      = t.get("source_object", "sign")
        if not content:
            continue
        dir_phrase = _DIRECTION_PHRASES.get(position, f"on the {position}")
        phrases.append(f"{src} {dir_phrase} says {content}")

    if not phrases:
        return ""

    sentence = ", ".join(phrases)
    return sentence[0].upper() + sentence[1:]


# ---------------------------------------------------------------------------
# Standalone helper — simple English pluralization
# ---------------------------------------------------------------------------

def _pluralize(word: str) -> str:
    irregulars = {"person": "people", "mouse": "mice", "knife": "knives"}
    if word in irregulars:
        return irregulars[word]
    if word.endswith(("s", "x", "z", "ch", "sh")):
        return word + "es"
    if word.endswith("y") and len(word) > 1 and word[-2] not in "aeiou":
        return word[:-1] + "ies"
    return word + "s"
